services:
  app:
    build:
      context: nest
      dockerfile: Dockerfile
    container_name: nest
    ports:
      - 3000:3000
    volumes:
      - ./nest:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  appgo:
    build:
      context: go
      dockerfile: Dockerfile
    container_name: go
    ports:
      - "50051:50051"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:host-gateway"
